import "../assets/extensions/filepond-plugin-file-validate-size/filepond-plugin-file-validate-size.min";
import "../assets/extensions/filepond-plugin-file-validate-type/filepond-plugin-file-validate-type.min";
import "../assets/extensions/filepond-plugin-image-crop/filepond-plugin-image-crop.min";
import "../assets/extensions/filepond-plugin-image-exif-orientation/filepond-plugin-image-exif-orientation.min";
import "../assets/extensions/filepond-plugin-image-filter/filepond-plugin-image-filter.min";
import "../assets/extensions/filepond-plugin-image-preview/filepond-plugin-image-preview.min";
import "../assets/extensions/filepond-plugin-image-resize/filepond-plugin-image-resize.min";
import "../assets/extensions/filepond/filepond";
import "../assets/static/js/pages/filepond";
